ConsumoWebAPI_IIS_MVC/Controllers/CadastroController.cs
using ConsumoWebAPI_IIS_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsumoWebAPI_IIS_MVC.Controllers
{
    public class CadastroController : Controller
    {
        [HttpGet]
        public IActionResult Cadastro(int? Id)
        {
            if (Id != null)
            {
                ViewBag.User = new ModelCadastro();
            }
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(ModelCadastro cadastro)
        {
            if (ModelState.IsValid)
            {
                cadastro.InserirUsuario();
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
    }
}

ConsumoWebAPI_IIS_MVC/Views/Cadastro/Cadastro.cshtml
@model ModelCadastro
@{
    Layout = null;
}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="icon" href="~/img/Icone.ico" />

<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="container">
            <br />
            <h3>Cadastro de Usuários</h3>
            <hr />

            <form asp-controller="Cadastro" asp-action="Cadastro" method="post">
                <input asp-for="Id" type="hidden" class="form-control" value="@try { @ViewBag.User.Id } catch { }" />

                <div class="form-row">
                    <div class="col col-8">
                        <label>Nome</label>
                        <input asp-for="Nome" type="text" class="form-control" value="@try { @ViewBag.User.Nome } catch { }" />
                        <span class="text-danger" asp-validation-for="Nome"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col col-4">
                        <label>Email</label>
                        <input asp-for="Email" type="text" class="form-control" value="@try { @ViewBag.User.Email } catch { }" />
                        <span class="text-danger" asp-validation-for="Email"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col col-4">
                        <label>Senha</label>
                        <input asp-for="Senha" type="password" class="form-control" value="@try { @ViewBag.User.Senha } catch { }" />
                        <span class="text-danger" asp-validation-for="Senha"></span>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col col-4">
                        <label>Confirme à Senha</label>
                        <input asp-for="ConfSenha" type="password" class="form-control" value="@try { @ViewBag.User.ConfSenha } catch { }" />
                        <span class="text-danger" asp-validation-for="ConfSenha"></span>
                    </div>
                </div>
                <br />
                <hr />
                <button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> Registrar</button>
                <button type="button" class="btn btn-dark ml-3 btn-sm" onclick="Desistir()"><i class="fa fa-times"></i> Desistir</button>


                <br /><hr />
                @DateTime.Now.Year - IURD Grupos e Membros - Por Paulo Bruno (Desenvolvedor) &reg;

            </form>
        </div>
    </div>
</div>

<script>
    function Desistir() {
        window.location.href = '../Home/Login';
    }
</script>