ConsumoWebAPI_IIS_MVC/Controllers/GrupoController.cs
using ConsumoWebAPI_IIS_MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace ConsumoWebAPI_IIS_MVC.Controllers
{
    public class GrupoController : Controller
    {
        // GET: GrupoController
        public ActionResult Index()
        {
            var wc = new WebClient();

            // Obs.: a API do daURL abaixo esta rodando no meu IIS.Express...
            var url = "http://192.168.1.146:5800/api/Grupo";

            // Chama WebService do tipo Rest...
            var res = wc.DownloadString(url);

            // Deserializa o Json e converte em Array de (Grupo)...
            Grupo[] Data = Newtonsoft.Json.JsonConvert.DeserializeObject<Grupo[]>(res);

            return View(Data);
        }

        // Retirei o Details...
        //============================================================================

        /* GET: GrupoController/Details/5
        public ActionResult Details(int id)
        {
            var wc = new WebClient();

            // Obs.: a API do daURL abaixo esta rodando no meu IIS.Express...
            // Concatenar com Id de Grupo...
            var url = "http://192.168.1.146:5800/api/Grupo/" + id.ToString();

            // Chama WebService do tipo Rest
            var res = wc.DownloadString(url);

            // Deserializa o Json e converte em Array de (Grupo)...
            Grupo Data = Newtonsoft.Json.JsonConvert.DeserializeObject<Grupo>(res);


            return View(Data);
        }  */

        // GET: GrupoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GrupoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Grupo Data)
        {
            try
            {
                var wc = new WebClient();
                var url = "http://192.168.1.146:5800/api/Grupo";

                // Serializa em formato "Json" os dados de (Grupo)...
                var json = Newtonsoft.Json.JsonConvert.SerializeObject(Data);

                // Configuração do WebClient para envio do Json
                wc.Headers.Add("Content-Type", "application/json");

                // Envio do Json ao WebService
                wc.UploadString(url, json);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GrupoController/Edit/5
        public ActionResult Edit(int id)
        {
            var wc = new WebClient();

            // Obs.: a API do daURL abaixo esta rodando no meu IIS.Express...
            // Concatenar com Id de Grupo...
            var url = "http://192.168.1.146:5800/api/Grupo/" + id.ToString();

            // Chama WebService do tipo Rest
            var res = wc.DownloadString(url);

            // Deserializa o Json e converte em um Objeto de (Grupo)...
            Grupo Data = Newtonsoft.Json.JsonConvert.DeserializeObject<Grupo>(res);

            // Passando o Grupo A View (Data)...
            return View(Data);
        }

        // POST: GrupoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Grupo Data)
        {
            try
            {
                var wc = new WebClient();
                // Concatenar com Id de Grupo...
                var url = "http://192.168.1.146:5800/api/Grupo/" + id.ToString();

                // Serializa em formato "Json" os dados de (Grupo)...
                var json = Newtonsoft.Json.JsonConvert.SerializeObject(Data);

                // Configuração do WebClient para envio do Json
                wc.Headers.Add("Content-Type", "application/json");

                // Envio do Json ao WebService com o método PUT
                wc.UploadString(url, "PUT", json);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: GrupoController/Delete/5
        public ActionResult Delete(int id)
        {
            var wc = new WebClient();

            // Obs.: a API do daURL abaixo esta rodando no meu IIS.Express...
            // Concatenar com Id de Grupo...
            var url = "http://192.168.1.146:5800/api/Grupo/" + id.ToString();

            // Chama WebService do tipo Rest
            var res = wc.DownloadString(url);

            // Deserializa o Json e converte em um Objeto de (Grupo)...
            Grupo Data = Newtonsoft.Json.JsonConvert.DeserializeObject<Grupo>(res);

            // Passando o Grupo A View (Data)...
            return View(Data);
        }

        // POST: GrupoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                var wc = new WebClient();
                // Concatenar com Id de Grupo...
                var url = "http://192.168.1.146:5800/api/Grupo/" + id.ToString();
                

                // Envio do Json ao WebService com o método DELETE
                wc.UploadString(url, "DELETE", "");

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ConsumoWebAPI_IIS_MVC/Controllers/GrupoUsuarioController.cs
using ConsumoWebAPI_IIS_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ConsumoWebAPI_IIS_MVC.Controllers
{
    public class GrupoUsuarioController : Controller
    {   
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Lista = new GrupoUsuario().RetornarListagem();
            return View();
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            CarregarDados();
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(GrupoUsuario grupo)
        {
            if(ModelState.IsValid)
            {
                grupo.Inserir();
                CarregarDados();
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }       
        
        [HttpGet]
        public IActionResult Filtro()
        {
            ViewBag.Lista = new GrupoUsuario().RetornarListagem();
            return View();
        }

        [HttpPost]
        public IActionResult Filtro(GrupoUsuario filtro)
        {
            try
            { 
            string grupoid = filtro.GruposId.ToString();
            ViewBag.Lista = new GrupoUsuario().RetornarListagemId(grupoid);
            return View();
            }
            catch(Exception)
            {
                return View();
            }
        }

        private void CarregarDados()
        {
            ViewBag.ListaGrupos = new GrupoUsuario().RetornarListaGrupo();
            ViewBag.ListaUsuarios = new GrupoUsuario().RetornarListaUsuario();
        }
    }          
}

ConsumoWebAPI_IIS_MVC/Controllers/UsuarioController.cs
using ConsumoWebAPI_IIS_MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace ConsumoWebAPI_IIS_MVC.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: UsuarioController
        public ActionResult Index()
        {
            var wc = new WebClient();

            // Obs.: a API do daURL abaixo esta rodando no meu IIS.Express...
            var url = "http://192.168.1.146:5800/api/Usuario";

            // Chama WebService do tipo Rest
            var res = wc.DownloadString(url);

            // Deserializa o Json e converte em Array de (Usuario)...
            Usuarios[] Data = Newtonsoft.Json.JsonConvert.DeserializeObject<Usuarios[]>(res);

            return View(Data);
        }

        // Retirei o Details...
        //========================================================================

        /* GET: UsuarioController/Details/5
        public ActionResult Details(int id)
        {
            var wc = new WebClient();

            // Obs.: a API do daURL abaixo esta rodando no meu IIS.Express...
            // Concatenar com Id de Grupo...
            var url = "http://192.168.1.146:5800/api/Usuario/" + id.ToString();

            // Chama WebService do tipo Rest
            var res = wc.DownloadString(url);

            // Deserializa o Json e converte em Array de (Usuario)...
            Usuarios Data = Newtonsoft.Json.JsonConvert.DeserializeObject<Usuarios>(res);


            return View(Data);
        }   */

        // GET: UsuarioController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuarios Data)
        {
            try
            {
                var wc = new WebClient();
                var url = "http://192.168.1.146:5800/api/Usuario";

                // Serializa em formato "Json" os dados de (Usuario)...
                var json = Newtonsoft.Json.JsonConvert.SerializeObject(Data);

                // Configuração do WebClient para envio do Json
                wc.Headers.Add("Content-Type", "application/json");

                // Envio do Json ao WebService
                wc.UploadString(url, json);

                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }

        // GET: UsuarioController/Edit/5
        public ActionResult Edit(int id)
        {
            var wc = new WebClient();

            // Obs.: a API do daURL abaixo esta rodando no meu IIS.Express...
            // Concatenar com Id de Grupo...
            var url = "http://192.168.1.146:5800/api/Usuario/" + id.ToString();

            // Chama WebService do tipo Rest
            var res = wc.DownloadString(url);

            // Deserializa o Json e converte em um Objeto de (Usuario)...
            Usuarios Data = Newtonsoft.Json.JsonConvert.DeserializeObject<Usuarios>(res);

            // Passando o Grupo A View (Data)...
            return View(Data);
        }

        // POST: UsuarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Usuarios Data)
        {
            try
            {
                var wc = new WebClient();
                // Concatenar com Id de Grupo...
                var url = "http://192.168.1.146:5800/api/Usuario/" + id.ToString();

                // Serializa em formato "Json" os dados de (Usuario)...
                var json = Newtonsoft.Json.JsonConvert.SerializeObject(Data);

                // Configuração do WebClient para envio do Json
                wc.Headers.Add("Content-Type", "application/json");

                // Envio do Json ao WebService com o método PUT
                wc.UploadString(url, "PUT", json);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsuarioController/Delete/5
        public ActionResult Delete(int id)
        {
            var wc = new WebClient();

            // Obs.: a API do daURL abaixo esta rodando no meu IIS.Express...
            // Concatenar com Id de Grupo...
            var url = "http://192.168.1.146:5800/api/Usuario/" + id.ToString();

            // Chama WebService do tipo Rest
            var res = wc.DownloadString(url);

            // Deserializa o Json e converte em um Objeto de (Usuario)...
            Usuarios Data = Newtonsoft.Json.JsonConvert.DeserializeObject<Usuarios>(res);

            // Passando o Grupo A View (Data)...
            return View(Data);
        }

        // POST: UsuarioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                var wc = new WebClient();
                // Concatenar com Id de Grupo...
                var url = "http://192.168.1.146:5800/api/Usuario/" + id.ToString();


                // Envio do Json ao WebService com o método DELETE
                wc.UploadString(url, "DELETE", "");

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ConsumoWebAPI_IIS_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IURD Grupos e Membros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="icon" href="~/img/Grupo.ico" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body onload="Logar()">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pagina Inicial</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Grupo" asp-action="Index">Grupos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Membros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GrupoUsuario" asp-action="Index">Grupos e Membros</a>
                        </li>
                    </ul>
                </div>
            </div>
            @using Microsoft.AspNetCore.Http
            @inject IHttpContextAccessor HttpContextAccessor
            <div id="logado"></div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - IURD Grupos e Membros - Por Paulo Bruno &reg;</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        function Logar() {
            let nome = '@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuario")';
            if (nome != "") {
                let DivNome = document.getElementById('logado');
                DivNome.innerHTML = "Logado(a): " + nome + " <a Href = '../Home/Login/0'><strong><em>(Sair)<em/><strong/><a/>";
                DivNome.style = "color: red; padding-top: -15px; font-size: 12px;";
            } else {
                window.location.href = '../Home/Login';
            }
        }
    </script>
    </body>
</html>